# Generated by Django 5.2.4 on 2026-04-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_board_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='earned_at',
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_high_prio_count',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_to_do_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='ticket_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
